Enhance phone-audio script with MDNS support and improve device connection handling

diff --git a/phone-audio b/phone-audio
--- a/phone-audio
+++ b/phone-audio
@@ -1,18 +1,133 @@
 #!/usr/bin/bash
 
+## CONSTANTS
+# Start of the string |     1-3 numbers with dots in between x4     | 1-5 number port
+IPADRESS_PORT_REGEX="^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}:[0-9]{1,5}$"
+IGNORED_ADB_LINES="List|of|devices|attached|device$"
+
+## FUNCTIONS
 stream_audio() {
     scrcpy --require-audio --no-video --no-window --no-control $args
 }
 
-read -p "Enter 'addr:port' to use WiFi otherwise USB is used: " answer
+connect_mdns() {
+    for line in $(avahi-browse --terminate --resolve --parsable --no-db-lookup _adb-tls-connect._tcp); do
+        if [[ $line != =* ]]; then
+            continue
+        fi
 
-# Start of the string |     1-3 numbers with dots in between x4     | 1-5 number port
-IPADRESS_PORT_REGEX="^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}:[0-9]{1,5}$"
+        IFS=';'; fields=($line); unset IFS;
+        uri="${fields[7]}:${fields[8]}"
+
+        echo "INFO: Attempting to connect to $uri"
+        local adb_result=$(adb connect $uri)
+        echo "$adb_result"
+
+        # Note: adb exits with 0 even if the connection fails,
+        # so I'm checking its output
+        if [[ $adb_result =~ connected ]]; then
+            return 0
+        fi
+    done
+
+    return 1
+}
+
+all_connected() {
+    local num_all=0
+    for line in $(adb devices); do
+        # Not a USB device
+        if [[ $line =~ $IGNORED_ADB_LINES ]]; then
+            continue
+        fi
+        (( num_all++ ))
+    done
+
+    echo $num_all
+    return $num_all
+}
+
+usb_connected() {
+    local num_usb=0
+    for line in $(adb devices); do
+        # Not a USB device
+        if [[ $line =~ $IGNORED_ADB_LINES || $line =~ $IPADRESS_PORT_REGEX ]]; then
+            continue
+        fi
+        (( num_usb++ ))
+    done
+
+    echo $num_usb
+    return $num_usb
+}
+
+tcp_connected() {
+local num_ip=0
+    for line in $(adb devices); do
+        # TCP/IP device
+        if [[ $line =~ $IPADRESS_PORT_REGEX ]]; then
+            (( num_ip++ ))
+        fi
+    done
+
+    echo $num_ip
+    return $num_ip
+}
+
+choose_device() {
+    echo "These devices are currently connected:"
+    local i=0
+    local adb_devices=()
+    for line in $(adb devices); do
+        # Not a USB device
+        if [[ $line =~ $IGNORED_ADB_LINES ]]; then
+            continue
+        fi
+        echo "$i: $line"
+        adb_devices+=($line)
+        (( i++ ))
+    done
+    read -p "Select the device to clone audio from [0, 1, 2, ...]: " device
+    if (( device > i )); then
+        echo "WARN: Invalid device selector"
+        choose_device
+        return
+    fi
+    args="--serial=${adb_devices[$device]}"
+}
+
+## MAIN
+
+read -p "Enter 'addr:port' to use WiFi otherwise USB, TCP/IP and MDNS is tried: " answer
 
 if [[ $answer =~ $IPADRESS_PORT_REGEX ]]; then
-    adb connect $answer
+    adb_result="$(adb connect $answer)"
+    echo "$adb_result"
+    if [[ $adb_result =~ connected ]]; then
+        echo "INFO: Successfully connected via IP"
+    else
+        echo "ERROR: Failed to connect to '$answer'"
+        exit 1
+    fi
+    args="--serial=$answer"
+elif (( $(all_connected) > 1 )); then
+    echo "INFO: Multiple devices found..."
+    choose_device
+elif (( $(usb_connected) == 1 )); then
+    echo "INFO: USB device found..."
+    args="-e"
+elif (( $(tcp_connected) == 1 )); then
+    echo "INFO: TCP/IP device found..."
     args="-e"
 else
-    args="-d"
+    echo "INFO: No devices found. Attempting to connect via MDNS"
+    connect_mdns
+    if (( $? == 1 )); then
+        echo "ERROR: Failed to find device via mdns. Ensure you have WiFi-Debugging enabled and are paired to the device"
+        exit 1
+    fi
+    echo "INFO: Device connected via mdns..."
+    args="--serial=$uri"
 fi
+
 stream_audio
